version: '3.9'

services:
  db:
    image: postgres:17.6
    container_name: gainzos-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gainzos-net

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: gainzos-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - apidata:/app/storage
    networks:
      - gainzos-net

  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: gainzos-dashboard
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - gainzos-net

networks:
  gainzos-net:

volumes:
  pgdata:
  apidata:
  cloudbeaver:  