version: '3.9'

services:
  db:
    image: postgres:17.6
    container_name: gainzos-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-gainzos}
      POSTGRES_USER: ${DATABASE_USERNAME:-gainzos}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-gainzos}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gainzos-net

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    container_name: gainzos-server
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - apidata:/app/storage
    networks:
      - gainzos-net

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: gainzos-web
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - gainzos-net

networks:
  gainzos-net:

volumes:
  pgdata:
  apidata:
  cloudbeaver:  